name: Print Github Contexts
on: push
jobs:
    prints:
        runs-on: ubuntu-latest
        env:
            G_HUB: ${{toJson(github)}}
        steps:
            - name: show github
              run: echo "${G_HUB}"
